import type { Plugin } from "vite";

function required(source:string,search:string,replacement:string){
  if(!source.includes(search))throw new Error(`Version 6.6 stable patch could not find: ${search.slice(0,120)}`);
  return source.replace(search,replacement);
}

export function version66Feature():Plugin{
  return {
    name:"ys-guys-version-6-6-stable",
    enforce:"pre",
    transform(source,id){
      if(!id.endsWith("/src/App.tsx"))return null;
      let code=source;
      code=required(code,'  return <div className="app"><style>{styles}</style><style>{reminderStyles}</style>',`  return <div className="app app66"><style>{styles}</style><style>{reminderStyles}</style><style>{version66Styles}</style>
      <aside className="side66"><button className="side66Logo" onClick={()=>go("home")}><img src="/ys-guys-logo.svg" alt="Y's Guys"/><div><b>Y'S GUYS</b><small>Summer 2026</small></div></button><nav><button className={view==="home"?"active":""} onClick={()=>go("home")}>⌂ <span>Home</span></button><button className={view==="profile"?"active":""} onClick={()=>myPlayer?openProfile(myPlayer):setShowMyPlayerPicker(true)}>◎ <span>My Player</span></button><button className={["community","voting","calendar","rules","games","players","leaders","season-stats"].includes(view)?"active":""} onClick={()=>go("community")}>◫ <span>Around the League</span></button><button className={["hof","timeline","awards","records","seasons"].includes(view)?"active":""} onClick={()=>go("hof")}>♛ <span>Hall of Fame / History</span></button></nav>{sessionToken&&<button className="side66Commissioner" onClick={()=>go("commissioner")}>Commissioner Mode</button>}<footer>HAVE FUN.<br/><b>WIN THE DAY.</b></footer></aside>`);
      code=required(code,'{view==="home" && <>','{view==="home" && <div className="home66"><section className="home66Intro"><div><small>VERSION 6.6 · HOME REDESIGN PREVIEW</small><h1>Our league is alive.</h1><p>Sunday is coming. Be part of it.</p></div><img src="/ys-guys-logo.svg" alt=""/></section>');
      code=required(code,'        {nextRun&&<QuickRsvp',`        {nextRun&&<section className="sunday66Info"><img src="/ys-guys-logo.svg" alt=""/><div><small>NEXT SUNDAY</small><h2>{formatRunDate(nextRun.date)}</h2><p>{nextRun.startTime} · {nextRun.location}</p>{nextRun.notes&&<em>{nextRun.notes}</em>}</div><aside><strong>{runCounts(nextRun).going}</strong><span>CONFIRMED</span><small>{Math.max(0,players.length-nextRun.rsvps.length)} awaiting response</small></aside></section>}
        {nextRun&&<QuickRsvp`);
      code=required(code,'        <div className="twoCol">',`        <section className="pulse66"><b>LEAGUE PULSE</b><div><small>SCORING LEADER</small><strong>{pointsLeader?.name??"—"} · {pointsLeader?.pts??0} PTS</strong></div><div><small>LATEST RESULT</small><strong>{latestFinal?latestFinal.teamA+" "+latestFinal.scoreA+"–"+latestFinal.scoreB+" "+latestFinal.teamB:"No final yet"}</strong></div><div><small>LEAGUE VOTE</small><strong>{activeRuleVote?"Open now":"No active vote"}</strong></div></section>
        <div className="twoCol">`);
      code=required(code,'        </div>\n      </>}\n\n      {view==="attendance"','        </div></div>}\n\n      {view==="attendance"');
      code=code.split('v6.5').join('v6.6').split('Version 6.5').join('Version 6.6').split('Commissioner Update').join('Home Redesign Preview');
      code+=`\nconst version66Styles=\`
:root{--v66navy:#06162f;--v66panel:#0c264b;--v66gold:#d5b45b;--v66cream:#f5efd9;--v66muted:#9fb0c6}
.app66{min-height:100vh;padding-left:244px;background:radial-gradient(circle at 75% 5%,rgba(42,88,141,.3),transparent 34%),linear-gradient(145deg,#051229,#081b39 58%,#06142c);color:var(--v66cream)}
.app66:before{content:"";position:fixed;inset:0;pointer-events:none;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:34px 34px}
.side66{position:fixed;z-index:50;inset:0 auto 0 0;width:244px;padding:24px 18px;background:linear-gradient(180deg,#081c3a,#06142b);border-right:1px solid rgba(213,180,91,.24);display:flex;flex-direction:column;box-shadow:18px 0 50px rgba(0,0,0,.2)}
.side66Logo{display:flex;align-items:center;gap:12px;background:transparent;border:0;color:white;text-align:left;padding:5px}.side66Logo img{width:58px;height:58px;object-fit:contain}.side66Logo div{display:grid}.side66Logo b{font-size:19px;letter-spacing:.08em}.side66Logo small{color:var(--v66muted);font-weight:800}.side66 nav{display:grid;gap:7px;margin-top:42px}.side66 nav button{display:flex;gap:12px;align-items:center;border:1px solid transparent;background:transparent;color:#aebdd0;border-radius:12px;padding:14px 12px;font-weight:900;text-align:left}.side66 nav button:first-letter{color:var(--v66gold)}.side66 nav button.active,.side66 nav button:hover{color:white;border-color:rgba(213,180,91,.38);background:linear-gradient(90deg,rgba(213,180,91,.18),transparent)}.side66Commissioner{margin-top:auto;padding:12px;border-radius:12px;border:1px solid var(--v66gold);background:transparent;color:var(--v66gold);font-weight:950}.side66 footer{margin-top:24px;color:#8496ad;font-size:11px;letter-spacing:.15em}.side66 footer b{color:var(--v66gold)}
.app66>.topbar{background:rgba(6,22,47,.88);backdrop-filter:blur(15px);border-bottom:1px solid rgba(213,180,91,.18)}.app66 main{max-width:1480px;margin:auto;padding:28px 32px 110px}.home66{display:grid;gap:18px}.home66Intro{display:flex;justify-content:space-between;align-items:center;padding:16px 4px 7px}.home66Intro small{color:var(--v66gold);font-weight:1000;letter-spacing:.12em}.home66Intro h1{margin:8px 0 5px;color:white;font-size:clamp(34px,5vw,60px);line-height:.95;text-transform:uppercase;letter-spacing:-.04em}.home66Intro p{margin:0;color:#a9b9cd}.home66Intro img{width:150px;height:100px;object-fit:contain;opacity:.13}.home66>.hero{display:none}
.sunday66Info{position:relative;overflow:hidden;display:grid;grid-template-columns:1fr auto;gap:24px;padding:28px;border:1px solid rgba(213,180,91,.62);border-radius:24px;background:linear-gradient(115deg,rgba(15,51,94,.98),rgba(7,28,59,.98));box-shadow:0 20px 60px rgba(0,0,0,.25)}.sunday66Info>img{position:absolute;width:320px;right:-20px;bottom:-70px;opacity:.055}.sunday66Info>div,.sunday66Info>aside{position:relative}.sunday66Info small{color:var(--v66gold);font-weight:950;letter-spacing:.12em}.sunday66Info h2{margin:6px 0;color:white;font-size:clamp(30px,4vw,50px);text-transform:uppercase}.sunday66Info p{color:#c3cede}.sunday66Info em{display:block;margin-top:14px;padding:10px 12px;border-left:2px solid var(--v66gold);background:rgba(255,255,255,.04);font-style:normal;color:#c5cfdd}.sunday66Info aside{display:grid;align-content:start;text-align:right}.sunday66Info aside strong{font-size:58px;line-height:.9;color:var(--v66gold)}.sunday66Info aside span{font-size:10px;font-weight:1000;letter-spacing:.14em}.sunday66Info aside small{margin-top:7px;color:#9eb0c7;letter-spacing:0}
.home66 .quickRsvp{border:1px solid rgba(213,180,91,.34);border-radius:20px;background:linear-gradient(145deg,rgba(12,38,75,.98),rgba(8,27,56,.98));color:white;box-shadow:0 14px 35px rgba(0,0,0,.18)}.home66 .quickRsvp>div:first-child{display:none}.home66 .quickChoices{width:100%;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.home66 .quickChoices button{min-height:54px;border-radius:12px;font-weight:1000}.home66 .quickChoices button.active{outline:2px solid var(--v66gold)}
.pulse66{display:grid;grid-template-columns:auto repeat(3,1fr);align-items:center;border:1px solid rgba(213,180,91,.25);border-radius:16px;overflow:hidden;background:linear-gradient(145deg,rgba(12,38,75,.98),rgba(8,27,56,.98))}.pulse66>b{padding:18px;color:var(--v66gold);letter-spacing:.12em}.pulse66>div{display:grid;padding:14px 18px;border-left:1px solid rgba(213,180,91,.16)}.pulse66 small{color:#94a7bf;font-size:9px;letter-spacing:.1em}.pulse66 strong{margin-top:4px;color:white}.home66 .panel,.home66 .myPlayerHome,.home66 .activeRuleVoteCard{background:linear-gradient(145deg,rgba(12,38,75,.98),rgba(8,27,56,.98))!important;color:var(--v66cream)!important;border:1px solid rgba(213,180,91,.24)!important;border-radius:20px!important;box-shadow:0 14px 34px rgba(0,0,0,.18)!important}.home66 .featureNews{min-height:320px;border:1px solid rgba(213,180,91,.35)}.home66 .featureNews h3{font-size:clamp(28px,3vw,44px);line-height:1;text-transform:uppercase}.home66 .powerPanel{display:none}.home66 .newsPanel{grid-column:1/-1}.app66 button{transition:transform .14s ease,border-color .14s ease,background .14s ease}.app66 button:active{transform:scale(.985)}
@media(max-width:900px){.app66{padding-left:0}.side66{display:none}.app66 main{padding:18px 16px 100px}.home66Intro img{width:95px}.pulse66{grid-template-columns:1fr 1fr}.pulse66>b{grid-column:1/-1}.pulse66>div{border-top:1px solid rgba(213,180,91,.16)}.bottomNav{display:grid!important;background:rgba(6,22,47,.97)!important;border-top:1px solid rgba(213,180,91,.25)!important}.bottomNav button{color:#98a9bf!important}.bottomNav button.active{color:var(--v66gold)!important}}
@media(max-width:600px){.home66Intro h1{font-size:34px}.sunday66Info{grid-template-columns:1fr;padding:20px}.sunday66Info aside{text-align:left;grid-template-columns:auto 1fr;gap:10px;align-items:end}.sunday66Info aside small{grid-column:1/-1}.home66 .quickChoices{grid-template-columns:1fr}.pulse66{grid-template-columns:1fr}.pulse66>b{grid-column:auto}.pulse66>div{border-left:0}.app66>.topbar .brand span small{display:none}}
\`;`;
      return {code,map:null};
    }
  };
}
